name: docker-action
on: 
    pull_request:
        branches:
            - main
    push:
        branches:
            - main
jobs: 
    build-docker-image:
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
            attestations: write
            id-token: write
        steps:
            - name: Building Docker Image
              run: docker buildx build -t web_app .

            - name: Run Tests
              uses: liatrio/github-actions/apprentice-action@master

            - name: Logging Into Dockerhub
              uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Extracting Docker Metadata
              id: meta
              uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
              with:
                images: supermouse101/liatrio-exercise
                tags: |
                    type=semver,pattern={{version}}

            - name: Push to Dockerhub
              id: push
              uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}

            - name: Generate artifact attestation
              uses: actions/attest-build-provenance@v3
              with:
                subject-name: index.docker.io/supermouse101/liatrio-exercise
                subject-digest: ${{ steps.push.outputs.digest }}
                push-to-registry: true